file:
  frontend-assets: src/assets/uploads # 上传文件保存路径

spring:
  redis:
    enabled: true # 可以通过这个配置开启或关闭Redis
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
